import {Colors} from './colors';

export const COLORS_LIGHT: Colors = {
  ['content-primary']: '#000000',
  ['content-secondary']: '#00000099',
  ['content-tertiary']: '#00000052',
  ['content-disabled']: '#00000038',
  ['content-primary-alt']: '#FFFFFF',
  ['content-secondary-alt']: '#FFFFFF99',
  ['content-accent']: '#00E5C4',
  ['content-positive']: '#00CE3A',
  ['content-warning']: '#FFDD59',
  ['content-negative']: '#FF5E57',
  ['content-black']: '#000000',
  ['content-black-secondary']: '#00000099',
  ['content-white']: '#FFFFFF',
  ['content-white-secondary']: '#FFFFFF99',
  ['background-primary']: '#F6F6F6',
  ['background-secondary']: '#FFFFFF',
  ['background-tertiary']: '#F6F6F6',
  ['background-success']: '#00E5C4',
  ['background-primary-alt']: '#000000',
  ['background-neutral']: '#EEEEEE',
  ['background-accent']: '#D9FEF8',
  ['background-positive']: '#DEFAE6',
  ['background-warning']: '#FAF5CC',
  ['background-negative']: '#FCCFC5',
  ['background-purple']: '#F7F1FD',
  ['border-primary']: '#E2E2E2',
  ['border-accent']: '#B2FCF1',
  ['border-positive']: '#ADF0C0',
  ['border-warning']: '#F5EB99',
  ['border-negative']: '#FABCAF',
  ['contextual-light-blue']: '#91EBF7',
  ['contextual-indigo']: '#6C82D0',
  ['contextual-yellow']: '#FFE548',
  ['contextual-medium-teal']: '#16ABAB',
  ['contextual-perwinkle-blue']: '#8BB6EF',
  ['contextual-coral']: '#FFA093',
  ['contextual-purple']: '#7517E6',
  ['gradient-top']: {
    colors: ['#00000099', '#00000000'],
    angle: 180,
  },
  ['gradient-bottom']: {
    colors: ['#00000000', '#00000099'],
    angle: 180,
  },
  ['gradient-blue-green']: {
    colors: ['#00BEFF', '#00FF94'],
    angle: 138,
  },
  ['gradient-skeleton']: {
    colors: ['#EEEEEE', '#E2E2E2', '#EEEEEE'],
    angle: 0,
  },
  ['overlay-default']: '#00000099',
  ['overlay-light']: '#FFFFFF',
  ['overlay-dark']: '#333333',
};
